### **NumPy - Práctica**

### **Ejercicio 1**
Cread dos matrices, A y B, de mida 5x5 con números enteros aleatorios entre 1 y 10. A continuación cread una tercera matriz, C, de mida 2x5 a partir de la última fila de la matriz A y la primera fila de la matriz B: la primera fila de la matriz C será la última de la matriz A, y la segunda fila de la matriz C será la primera fila de la matriz B. Mostrad por pantalla el resultado obtenido.

In [0]:
from numpy import random
import numpy as np
A = random.randint(1,11,(5,5))
print(A)
B = random.randint(1,11,(5,5))
print(B) 
C = np.array([A[4,:],B[0,:]])
print(C)

[[5 4 2 7 5]
 [4 7 5 3 4]
 [3 3 8 2 8]
 [3 2 2 9 6]
 [5 4 7 7 9]]
[[5 3 3 4 3]
 [4 5 6 9 4]
 [7 2 2 7 9]
 [6 8 5 1 1]
 [9 9 4 7 4]]
[[5 4 7 7 9]
 [5 3 3 4 3]]


### **Ejercicio 2**

Dadas las matrices A y B del ejercicio anterior, mostrad por pantalla el resultado de las siguientes operaciones:

Sumar las dos matrices
Restar la matriz B de la matriz A
Multiplicar las dos matrices
Explicad brevemente cuál es el método de multiplicación escogido y porque.

In [0]:
# Respuesta
print(A+B)
print(A-B)

print(A*B) # Multiplica la primera posición con la primera posición y así <- Este sería el método correcto para Arrays
print(np.mat(A)*np.mat(B)) # Multiplicación matricial, filas * Columnas <- Este sería el método correcto para Matrices

[[10  7  5 11  8]
 [ 8 12 11 12  8]
 [10  5 10  9 17]
 [ 9 10  7 10  7]
 [14 13 11 14 13]]
[[ 0  1 -1  3  2]
 [ 0  2 -1 -6  0]
 [-4  1  6 -5 -1]
 [-3 -6 -3  8  5]
 [-4 -5  3  0  5]]
[[25 12  6 28 15]
 [16 35 30 27 16]
 [21  6 16 14 72]
 [18 16 10  9  6]
 [45 36 28 49 36]]
[[142 140  98 112  76]
 [137 117  95 145 104]
 [167 128  85 153 127]
 [145 149  94  95  68]
 [213 186 124 175 137]]


### **Ejercicio 3**
Ordenad la matriz bidimensional [[5,1,7], [0,7,4], [7,23,1]] por columnas utilizando como algoritmo de ordenación el Heapsort.

Nota: Para resolver este ejercicio os puede ser de ayuda la función sort de Numpy que nos permite ordenar los elementos de un array N-dimensional.

In [2]:
# Respuesta
D = np.array([[5,1,7], [0,7,4], [7,23,1]] )
print(D)
D = np.sort(D,axis=0,  kind='heapsort')
print(D)

NameError: ignored

### **Ejercicio 4**
Cread una matriz, I, de mida 10x10 donde todos sus elementos tendrán el valor 0 utilizando generadores de matrices de numpy. Modificad la matriz anterior de tal forma que I[i, j] = i * j para todo i y j pares, es decir, para todas las posiciones donde tanto i como j son pares.

In [0]:
# Respuesta
I = np.zeros((10,10))
print(I)

for i in range(10):
  for j in range(10):
    if(i%2==0 and j%2==0):
      I[i][j]=i*j

print(I)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  4.  0.  8.  0. 12.  0. 16.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  8.  0. 16.  0. 24.  0. 32.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 12.  0. 24.  0. 36.  0. 48.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 16.  0. 32.  0. 48.  0. 64.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


### **Ejercicio 5**
Una técnica que se aplica en muchos algoritmos de compresión de imagenes, como fase previa a la compresión, es asignar a cada píxel de la imagen el valor medio de sus N píxeles vecinos. Nosotros implementaremos una versión simplificada de esta técnica.

Una imagen se puede ver como una matriz bidimensional donde cada elemento de la matriz corresponde a un valor de un píxel de la imagen. Por ejemplo, si generamos una imágen a partir de la matriz que os proporcionamos más abajo, veremos una imagen en escala de grises. Para probarlo podéis ejecutar la siguiente intrucción: generate_png(pixels). Esto os generará un fichero, generated.png.

Cread una nueva matriz, pixels_transform, a partir de la matriz pixels donde el valor de cada elemento de pixels_transform se calculará como la media de los valores de los 4 vecinos más próximos del correspondiente píxel en la matriz pixels. Veámoslo formalmente:

```
pixels_transform[i, j] = (pixels[i, j-1] + pixels[i-1, j] + pixels[i, j+1] + pixels[i+1, j]) / 4
```


Consideraciones:

Consideramos como los 4 vecinos más próximos los píxeles anterior (izquierda), superior (arriba), posterior (derecha) e inferior (abajo) del píxel que estamos analizando.
Si no podemos acceder a alguno de estos vecinos (e.g. el píxel (0, 0) no tiene vecinos anterior y superior), asumimos que los valores que nos faltan son 0.
Mostrad por pantalla el resultado obtenido.

Nota: Para resolver este ejercicio necesitamos recorer todos los elementos de la matriz pixels y para cada elemento tenemos que comprobar los valores de sus 4 vecinos. Necesitaremos un bloque condicional (if) para cada uno de los elementos vecinos.

In [0]:
from PIL import Image
import numpy as np

pixels = [
   [54, 93, 71, 168],
   [122, 54, 167, 93],
   [71, 167, 54, 122],
   [167, 82, 23, 54]
]

# Podéis utilizar la siguiente función para generar una imagen a partir de un array de píxeles.
# Por ejemplo, generate_png(pixels)
def generate_png(matriz):
    # Nos aseguramos que la matriz es un array de numpy
    pixels = np.array(matriz, dtype=np.uint8)

    # Utilizamos la librería PIL para crear una imagen a partir de una array de píxeles
    imagen = Image.fromarray(pixels)
    imagen.save('generated.png')

generate_png(pixels)

In [0]:
# Respuesta
def generarNuevaMatriz(matriz):
  pixels_transform = np.zeros((len(matriz[0]),len(matriz[1])))
  for i in range(len(matriz[0])):
    for j in range(len(matriz[1])):
      if(i-1<0):
        arriba = 0
      else: 
        arriba = pixels[i-1][j]
      if (i+1>=len(matriz[0])):
        abajo = 0 
      else: 
        abajo = pixels[i+1][j]
      if(j-1<0):
        izquierda = 0
      else: 
        izquierda = pixels[i][j-1]
      if(j+1>=len(matriz[1])): 
        derecha = 0 
      else: 
        derecha = pixels[i][j+1]
      pixels_transform[i][j] = (arriba + abajo +derecha +izquierda)/ 4
      
  return (pixels_transform)

nuevaMatriz = generarNuevaMatriz(pixels)
print(nuevaMatriz)


[[ 53.75  44.75 107.    41.  ]
 [ 44.75 137.25  68.   114.25]
 [114.    65.25 119.75  50.25]
 [ 38.25  89.25  47.5   36.25]]
